# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: False

# Ignore files and directories for tree
# and "Contents of ..." sections
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"
  - "src/"
  - "HR-VPP/"
  - "dem/"
  - "FLG/"
  - "mosaics/"
  - "products/" 
  - "extract_test/"
  - "jeanzay/" 
  - "qgis/"
  - "notebooks/" 

# Ignore files and directories for "Contents of ..." section
ignore-content:
  - "README.md"
  - "LICENSE"
  - "tests/"
